import { z } from 'zod';
import { db } from './db';
import { safeCsvCell } from './validation';

const backupSchema=z.object({format:z.literal('palletflow-lab-backup'),version:z.literal(1),createdAt:z.string(),receptions:z.array(z.record(z.string(),z.unknown())),pallets:z.array(z.record(z.string(),z.unknown())),parcels:z.array(z.record(z.string(),z.unknown())),locations:z.array(z.record(z.string(),z.unknown())),movements:z.array(z.record(z.string(),z.unknown()))});

function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}

export async function exportCsv(){const pallets=await db.pallets.toArray();const header=['Código','Estado','Artículo','Bultos','Unidades','Ubicación','Operario'];const rows=pallets.map((p)=>[p.code,p.status,p.article,p.parcels,p.units,p.locationId??'',p.operator]);const csv=[header,...rows].map((row)=>row.map(safeCsvCell).join(',')).join('\n');download(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}),'palletflow-inventario.csv');}
export async function exportExcel(){
  const [receptions,pallets,parcels,locations]=await Promise.all([db.receptions.toArray(),db.pallets.toArray(),db.parcels.toArray(),db.locations.toArray()]);
  const escape=(value:unknown)=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
  const safe=(value:unknown)=>escape(/^[=+\-@\t\r]/.test(String(value??''))?`'${value}`:value);
  const cell=(value:unknown,type:'String'|'Number'='String')=>`<Cell><Data ss:Type="${type}">${type==='Number'?Number(value||0):safe(value)}</Data></Cell>`;
  const sheet=(name:string,headers:string[],rows:unknown[][],numberColumns:number[]=[])=>`<Worksheet ss:Name="${name}"><Table><Row>${headers.map(v=>cell(v)).join('')}</Row>${rows.map(row=>`<Row>${row.map((value,index)=>cell(value,numberColumns.includes(index)?'Number':'String')).join('')}</Row>`).join('')}</Table><AutoFilter xmlns="urn:schemas-microsoft-com:office:excel" x:Range="R1C1:R${rows.length+1}C${headers.length}"/></Worksheet>`;
  const palletRows=pallets.map(p=>{const reception=receptions.find(r=>r.id===p.receptionId);const location=locations.find(l=>l.id===p.locationId);return [reception?.reference,reception?.vehicle,p.number,p.code,p.status,p.mocacota||p.article,p.color,p.size,p.expectedParcels||'',p.parcels,p.units,location?.code||'',p.scanClosedAt||'',p.floorAt||'',p.operator]});
  const parcelRows=parcels.map(box=>{const pallet=pallets.find(p=>p.id===box.palletId);const reception=receptions.find(r=>r.id===pallet?.receptionId);return [reception?.reference,pallet?.number,pallet?.code,box.code,box.mocacota||box.article,box.color,box.size,box.units,box.anomalous?'Sí':'No',box.operator,box.createdAt]});
  const receptionRows=receptions.map(r=>{const rows=pallets.filter(p=>p.receptionId===r.id);return [r.reference,r.vehicle,r.receivedAt,r.status,r.expectedPallets,rows.length,rows.filter(p=>p.scanClosedAt).length,rows.filter(p=>p.status==='ubicado').length,rows.reduce((sum,p)=>sum+p.parcels,0),rows.reduce((sum,p)=>sum+p.units,0)]});
  const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet" xmlns:x="urn:schemas-microsoft-com:office:excel">${sheet('Recepciones',['Recepción','Matrícula','Fecha','Estado','Palés previstos','Palés creados','Palés cerrados','Palés ubicados','Bultos','Unidades'],receptionRows,[4,5,6,7,8,9])}${sheet('Palés',['Recepción','Matrícula','Nº palé','QR único','Estado','Mocacota','Color','Talla','Bultos previstos','Bultos leídos','Unidades','Ubicación','Cerrado','En suelo','Operario'],palletRows,[2,8,9,10])}${sheet('Bultos',['Recepción','Nº palé','QR palé','Código de bulto','Mocacota','Color','Talla','Unidades','Anomalía','Operario','Fecha/hora'],parcelRows,[1,7])}</Workbook>`;
  download(new Blob([xml],{type:'application/vnd.ms-excel'}),`palletflow-packlist-${new Date().toISOString().slice(0,10)}.xls`);
}
export async function createBackup(downloadFile=true){const backup={format:'palletflow-lab-backup' as const,version:1 as const,createdAt:new Date().toISOString(),receptions:await db.receptions.toArray(),pallets:await db.pallets.toArray(),parcels:await db.parcels.toArray(),locations:await db.locations.toArray(),movements:await db.movements.toArray()};if(downloadFile)download(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),`palletflow-backup-${new Date().toISOString().slice(0,10)}.json`);return backup;}
export async function restoreBackup(text:string){await createBackup(true);const parsed=backupSchema.parse(JSON.parse(text));await db.transaction('rw',[db.receptions,db.pallets,db.parcels,db.locations,db.movements],async()=>{await Promise.all([db.receptions.clear(),db.pallets.clear(),db.parcels.clear(),db.locations.clear(),db.movements.clear()]);await db.receptions.bulkPut(parsed.receptions as never[]);await db.pallets.bulkPut(parsed.pallets as never[]);await db.parcels.bulkPut(parsed.parcels as never[]);await db.locations.bulkPut(parsed.locations as never[]);await db.movements.bulkPut(parsed.movements as never[]);});}
